### ISSUE TITLE
Crashes after viewing 10 pics or more

### ISSUE THREAD

**Issue by FrozenAlex** [Futuremappermydud/Nya-quest#3]
After viewing 10+ pictures my beatsaber seems to crash constantly. I checked it on the commit before mine and it has the same issue.
It seems to always crash on this line in ModifiersMenu.cpp. I'm trying to debug it but still can't find the reason why it crashes.
```cpp
auto arr = il2cpp_utils::vectorToArray(bytes);
```

**Comment by Futuremappermydud** [comment]
I thought I fixed that aaaaaaa

**Comment by FrozenAlex** [comment]
I think I solved the issue
```cpp
this->NYA->set_sprite(QuestUI::BeatSaberUI::VectorToSprite(bytes));
```
does not seem to leak and we don't need `auto arr = il2cpp_utils::vectorToArray(bytes);` anymore

**Comment by FrozenAlex** [comment]
Yep that fixes it

**Comment by Futuremappermydud** [comment]
Make a pr

**Comment by FrozenAlex** [comment]
I tested it on like 40 pics so it is fine
